require("options")
require("keymaps")
require("lsp")

require("plugins.dap")
require("plugins.floaterminal")
require("plugins.fzf")
require("plugins.gitsigns")
require("plugins.mini-completion")
require("plugins.mini-snippets")
require("plugins.nvim-autopairs")
require("plugins.nvim-tree")
require("plugins.which-key")
