require("options")
require("keymaps")
require("lsp")

require("plugins.blink")
require("plugins.dap")
require("plugins.dapui")
require("plugins.floaterminal")
require("plugins.fzf")
require("plugins.gitsigns")
require("plugins.kulala")
-- require("plugins.mini-snippets")
require("plugins.nvim-autopairs")
require("plugins.nvim-tree")
require("plugins.treesitter")
require("plugins.tsautotag")
require("plugins.which-key")
