local gitsigns = require("gitsigns")
gitsigns.setup()

vim.keymap.set("n", "]h", gitsigns.next_hunk, { desc = "Next git hunk" })
vim.keymap.set("n", "[h", gitsigns.prev_hunk, { desc = "Previous git hunk" })
vim.keymap.set("n", "<leader>hs", gitsigns.stage_hunk, { desc = "Stage hunk" })
vim.keymap.set("n", "<leader>hr", gitsigns.reset_hunk, { desc = "Reset hunk" })
vim.keymap.set("n", "<leader>hp", gitsigns.preview_hunk, { desc = "Preview hunk" })
vim.keymap.set("n", "<leader>hb", function() gitsigns.sblame_line({ full = true }) end, { desc = "Blame line" })
vim.keymap.set("n", "<leader>tb", gitsigns.toggle_current_line_blame, { desc = "Toggle inline blame" })
vim.keymap.set("n", "<leader>hd", gitsigns.diffthis, { desc = "Diff this" })
