local gitsigns = require("gitsigns")
gitsigns.setup()

vim.keymap.set("n", "]h", gitsigns.next_hunk, { desc = "Next git hunk" })
vim.keymap.set("n", "[h", gitsigns.prev_hunk, { desc = "Previous git hunk" })
vim.keymap.set("n", "<leader>gs", gitsigns.stage_hunk, { desc = "Stage hunk" })
vim.keymap.set("n", "<leader>gr", gitsigns.reset_hunk, { desc = "Reset hunk" })
vim.keymap.set("n", "<leader>gp", gitsigns.preview_hunk, { desc = "Preview hunk" })
vim.keymap.set("n", "<leader>gb", function() gitsigns.sblame_line({ full = true }) end, { desc = "Blame line" })
vim.keymap.set("n", "<leader>tb", gitsigns.toggle_current_line_blame, { desc = "Toggle inline blame" })
vim.keymap.set("n", "<leader>gd", gitsigns.diffthis, { desc = "Diff this" })
